### ISSUE TITLE
Make `FromUrlEncodingError` public?

### ISSUE THREAD

**Issue by songday** [kornelski/rust_urlencoding#2]
At urlencoding `1.1` version, `FromUrlEncodingError` is public.
I can implement `From<urlencoding::FromUrlEncodingError>` for my custom `Error` struct
thus I can simply use `decode` method with `?` symbol

then I upgraded to `1.3`, `FromUrlEncodingError` becomes private

**Comment by kornelski** [comment]
Fixed
